version: "3.7"
services:
  app:
    build:
      args:
        user: webbanlinhkien
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: webbanlinhkien
    container_name: webbanlinhkien-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - webbanlinhkien

  db:
    image: mysql:5.7
    container_name: webbanlinhkien-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33064:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - webbanlinhkien

  nginx:
    image: nginx:alpine
    container_name: webbanlinhkien-nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - webbanlinhkien

networks:
  webbanlinhkien:
    driver: bridge
